// string_table_id.h

#pragma once


// -----------------------------------------------------------------------
// main frame
#define RSID_STR_MAIN_LANGUAGE                   40051
#define RSID_STR_MAIN_REPLAY_FOLDER_GROUP        40052
#define RSID_STR_MAIN_REPLAY_FOLDER_AUTO         40053
#define RSID_STR_MAIN_REPLAY_FOLDER_REF_BUTTON   40054
#define RSID_STR_MAIN_REPLAY_FOLDER_DONE_LABEL   40055
#define RSID_STR_MAIN_SELF_NAME_GROUP            40056
#define RSID_STR_MAIN_SELF_NAME_AUTO_BUTTON      40057
#define RSID_STR_MAIN_ANALYZE_BUTTON             40058
#define RSID_STR_MAIN_DATE_TEMPLATE_GROUP        40059
#define RSID_STR_MAIN_DATE_TEMPLATE_TITLE        40060
#define RSID_STR_MAIN_DATE_TEMPLATE_HISTORY      40061
#define RSID_STR_MAIN_DATE_TEMPLATE_NOTICE       40062
#define RSID_STR_MAIN_DATE_MOVE_BUTTON           40063
#define RSID_STR_MAIN_OPPONENT_SEARCH_BUTTON     40064
#define RSID_STR_MAIN_OPPONENT_COPY_BUTTON       40065
#define RSID_STR_MAIN_OPPONENT_LIMIT_CHECK       40067
#define RSID_STR_MAIN_OPPONENT_LIST_COLUMN_NAME  40068
#define RSID_STR_MAIN_OPPONENT_LIST_COLUMN_COUNT 40069

#define RSID_STR_MAIN_REPLAY_FOLDER_REF_FOLDER_DIALOG_DESCRIPTION 40201

#define RSID_STR_MAIN_AUTO_INPUT_CONFIRM_CAP     40212
#define RSID_STR_MAIN_AUTO_INPUT_CONFIRM_MSG     40213
#define RSID_STR_MAIN_DATE_MOVE_CONFIRM_CAP      40214
#define RSID_STR_MAIN_DATE_MOVE_CONFIRM_MSG      40215
#define RSID_STR_MAIN_DATE_MOVE_DONE_CAP         40216
#define RSID_STR_MAIN_DATE_MOVE_DONE_MSG         40217
#define RSID_STR_MAIN_OPPONENT_COPY_CONFIRM_CAP  40218
#define RSID_STR_MAIN_OPPONENT_COPY_CONFIRM_MSG  40219
#define RSID_STR_MAIN_OPPONENT_COPY_DONE_CAP     40220
#define RSID_STR_MAIN_OPPONENT_COPY_DONE_MSG     40221
#define RSID_STR_MAIN_SELF_NAME_AUTO_CONFIRM_CAP 40222
#define RSID_STR_MAIN_SELF_NAME_AUTO_CONFIRM_MSG 40223
#define RSID_STR_MAIN_REPLAY_FOLDER_IS_EMPTY_CAP 40224
#define RSID_STR_MAIN_REPLAY_FOLDER_IS_EMPTY_MSG 40225
#define RSID_STR_MAIN_REPLAY_FILE_IS_EMPTY_CAP   40226
#define RSID_STR_MAIN_REPLAY_FILE_IS_EMPTY_MSG   40227
#define RSID_STR_MAIN_SELF_NAME_IS_EMPTY_CAP     40228
#define RSID_STR_MAIN_SELF_NAME_IS_EMPTY_MSG     40229


// -----------------------------------------------------------------------
// analyze dialog
#define RSID_STR_ANALYZE_ALL_CHARACTER 44051

#define RSID_STR_ANALYZE_LIST_COLUMN_OPPONENT         44061
#define RSID_STR_ANALYZE_LIST_COLUMN_COUNT_OF_MATCHES 44062
#define RSID_STR_ANALYZE_LIST_COLUMN_WIN              44063
#define RSID_STR_ANALYZE_LIST_COLUMN_WINNING_RATE     44064
#define RSID_STR_ANALYZE_LIST_COLUMN_LOSE             44065
#define RSID_STR_ANALYZE_LIST_COLUMN_DRAW             44066
#define RSID_STR_ANALYZE_LIST_COLUMN_UNKNOWN          44067
#define RSID_STR_ANALYZE_LIST_COLUMN_1P               44068
#define RSID_STR_ANALYZE_LIST_COLUMN_2P               44069
#define RSID_STR_ANALYZE_LIST_COLUMN_DATE             44070
#define RSID_STR_ANALYZE_LIST_COLUMN_1P_WIN           44071
#define RSID_STR_ANALYZE_LIST_COLUMN_2P_WIN           44072

#define RSID_STR_ANALYZE_COMBO_ALL_CHARACTER 44081
#define RSID_STR_ANALYZE_COMBO_BY_OPPONENT   44082

#define RSID_STR_ANALYZE_LOADING_LABEL  44091
#define RSID_STR_ANALYZE_USING_CARACTER 44092

#define RSID_STR_ANALYZE_REPLAY_FILE_LOADING_ERROR_CAP 44101
#define RSID_STR_ANALYZE_REPLAY_FILE_LOADING_ERROR_MSG 44102


// -----------------------------------------------------------------------
// 50000
// message
#define RSID_STR_MSG_INTERNAL_ERROR            50001
#define RSID_STR_MSG_UNEXPECTED_ERROR          50011
#define RSID_STR_MSG_UNEXPECTED_ERROR_CAP      50012
#define RSID_STR_MSG_LANGUAGE_CHANGE_ERROR     50101
#define RSID_STR_MSG_LANGUAGE_CHANGE_ERROR_CAP 50102

#define RSID_STR_MSG_ERROR_CAPTION             50201
#define RSID_STR_MSG_FILE_OPERATION_ERROR      50211
